// Project-specific Env bindings (merged with the types generated by `pnpm cf-typegen`).
interface Env {
  DB: D1Database
  /** Worker secret — HMAC pepper applied before PBKDF2 (spec §8.1). Never logged, never committed. */
  PASSWORD_PEPPER: string
  APP_TIMEZONE: string
  REGISTRATION_ENABLED: string
  PBKDF2_ITERATIONS: string
  SESSION_TTL_DAYS: string
}
